# Generated by Django 5.1.5 on 2025-04-28 12:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_mun', models.CharField(max_length=7)),
                ('nm_mun', models.CharField(max_length=100)),
                ('cd_uf', models.CharField(max_length=2)),
                ('nm_uf', models.CharField(max_length=50)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
            ],
        ),
    ]
