# Generated by Django 5.1.5 on 2025-05-12 18:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brasil',
            fields=[
                ('cd_mun', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nm_mun', models.CharField(max_length=100)),
                ('cd_uf', models.CharField(max_length=2)),
                ('nm_uf', models.CharField(max_length=50)),
                ('sigla_uf', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
            ],
            options={
                'ordering': ['cd_uf', 'nm_mun'],
                'indexes': [models.Index(fields=['cd_uf', 'nm_mun'], name='brutb_brasi_cd_uf_1d7898_idx')],
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('estado', models.CharField(max_length=2)),
                ('codigo_rebanho', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brutb.brasil')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_propriedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['municipio'],
                'indexes': [models.Index(fields=['municipio'], name='brutb_propr_municip_3ef20a_idx')],
            },
        ),
    ]
