# Generated by Django 5.1.5 on 2025-05-04 12:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brasil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cd_mun", models.CharField(max_length=7)),
                ("nm_mun", models.CharField(max_length=100)),
                ("cd_uf", models.CharField(max_length=2)),
                ("nm_uf", models.CharField(max_length=50)),
                ("sigla_uf", models.CharField(max_length=2)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Propriedades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateTimeField(auto_now_add=True)),
                ("atualizado", models.DateTimeField(auto_now=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="brutb.brasil"
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_propriedades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
