# Generated by Django 5.1.5 on 2025-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brutb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brasil',
            new_name='Municipio',
        ),
        migrations.RenameIndex(
            model_name='municipio',
            new_name='brutb_munic_cd_uf_bd41fa_idx',
            old_name='brutb_brasi_cd_uf_1d7898_idx',
        ),
    ]
