# Generated by Django 5.1.5 on 2025-04-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brutb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brasil',
            old_name='mpoly',
            new_name='geom',
        ),
    ]
