# Generated by Django 5.1.5 on 2025-05-15 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brutb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='codigo_rebanho',
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='cod_rebanho_estudo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1100015001), django.core.validators.MaxValueValidator(5300108500)]),
        ),
    ]
