# Generated by Django 5.1.5 on 2025-05-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=11)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("12", "AC"),
                            ("27", "AL"),
                            ("13", "AM"),
                            ("16", "AP"),
                            ("29", "BA"),
                            ("23", "CE"),
                            ("53", "DF"),
                            ("32", "ES"),
                            ("52", "GO"),
                            ("21", "MA"),
                            ("31", "MG"),
                            ("50", "MS"),
                            ("51", "MT"),
                            ("15", "PA"),
                            ("25", "PB"),
                            ("26", "PE"),
                            ("22", "PI"),
                            ("41", "PR"),
                            ("33", "RJ"),
                            ("24", "RN"),
                            ("11", "RO"),
                            ("14", "RR"),
                            ("43", "RS"),
                            ("42", "SC"),
                            ("28", "SE"),
                            ("35", "SP"),
                            ("17", "TO"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sistema",
                    models.CharField(
                        choices=[
                            ("Brucelose", "Brucelose"),
                            ("Tuberculose", "Tuberculose"),
                            ("Brucelose e Tuberculose", "Brucelose e Tuberculose"),
                        ],
                        max_length=23,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
