# Generated by Django 5.1.5 on 2025-04-19 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conta", "0002_rename_contas_conta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Conta",
            new_name="Perfil",
        ),
    ]
