# Generated by Django 5.1.5 on 2025-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_rename_conta_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('AC', '12'), ('AL', '27'), ('AM', '13'), ('AP', '16'), ('BA', '29'), ('CE', '23'), ('DF', '53'), ('ES', '32'), ('GO', '52'), ('MA', '21'), ('MG', '31'), ('MS', '50'), ('MT', '51'), ('PA', '15'), ('PB', '25'), ('PE', '26'), ('PI', '22'), ('PR', '41'), ('RJ', '33'), ('RN', '24'), ('RO', '11'), ('RR', '14'), ('RS', '43'), ('SC', '42'), ('SE', '28'), ('SP', '35'), ('TO', '17')], max_length=2),
        ),
    ]
